### ISSUE TITLE
Generating 2FA recovery codes leads to 404

### ISSUE THREAD

**Issue by djhoese** [pypa/warehouse#11534]
**Describe the bug**
I haven't logged in to PyPI (pypi.org) in a while, but needed to today. I already had 2FA enabled but the site told me that I hadn't generated recovery codes. I also got an email about it. Both links point to `https://pypi.org/manage/account/recovery-codes/generate/?` which leads me to a 404 page.

**Expected behavior**
2FA recovery codes are shown

**To Reproduce**
My user account is "dhoese".

Go to the 2FA recovery code generation page at https://pypi.org/manage/account/recovery-codes/generate/? (at least for my account).

**My Platform**

Firefox on PopOS.

**Additional context**

**Comment by frankie567** [comment]
I confirm that I can't connect neither, the MFA API (https://pypi.org/account/webauthn-authenticate/options/) also returns a 404.

Besides, it seems that legacy API have gone missing, like https://pypi.org/pypi?%3Aaction=list_classifiers, which breaks some build tooks like Flit.

**Comment by di** [comment]
This was due to https://github.com/python/pypi-infra/pull/74. I've rolled back our CDN config for now, so this should be resolved, and we'll revert that or fix it in https://github.com/python/pypi-infra/pull/85.

**Comment by di** [comment]
It is fixed, I manually rolled back the CDN configuration, that PR is just to capture what I did in our infra-as-code repo.

**Comment by di** [comment]
The right URL (for now) is https://pypi.org/manage/account/recovery-codes/generate

**Comment by djhoese** [comment]
I still get a 404 with that (with a `/?` appended or not) and after Ctrl + Shift + R to do a hard refresh.

**Comment by djhoese** [comment]
Ah of course, I've had problems with that with Firefox on this system. Switching to Chrome worked. It was also a little confusing at first since you still get the 404 if you go to directly to the generate URL without being signed in. Had to go back to the main page, log in, then go to the URL.

Thanks again.
