### ISSUE TITLE
Email verification issue

### ISSUE THREAD

**Issue by groupdocscloud** [pypa/warehouse#4793]
I am unable to publish any package as getting an email verification issue, no emails are being sent to neither my inbox nor spam folder. Please do the needful. Thanks.

PyPI username: groupdocscloud

**Comment by groupdocscloud** [comment]
Hi @ewdurbin 
Thanks for your feedback. We have investigated and found that the emails reached our email server, but were rejected as SPAM because they failed the SPF Check (Sender ID). We will appreciate it if Pypi.org update their SPF record in their DNS to include the IP they sent the email from - 54.240.27.10. You can verify that the SPF authentication fails using the following tool. Thanks.
https://mxtoolbox.com/SuperTool.aspx?action=spf%3apypi.org%3a54.240.27.10&run=toolpage

**Comment by ewdurbin** [comment]
DMARC is something I'm still working to fully understand :)

@dstufft may be able to better explain, but our Return-Path for these emails are on the `ses.pypi.org` domain, which [does properly pass SPF with the sending IP](https://mxtoolbox.com/SuperTool.aspx?action=spf%3apypi.org%3a54.240.27.10&run=toolpage#).

It sounds like your mail server may be checking SPF on the wrong domain (pypi.org vs ses.pypi.org), or that we should indeed have `include:amazonses.com` as part of the pypi.org SPF record. I'll wait for @dstufft's input before making any changes.

**Comment by dstufft** [comment]
It certainly sounds like the receiving server is not correctly checking SPF records, and is checking the envelope ``FROM`` address instead of the ``MAIL FROM`` address. That being said, the risk of adding the header to make it work with the envelope information instead of the ``MAIL FROM`` is very small, so I'm fine adding it.

**Comment by groupdocscloud** [comment]
@ewdurbin
As per above comments, it seems you are updating your email server configuration. Please let us know once it is done, so we will verify our email id and start pushing our packages. Thanks.

**Comment by ewdurbin** [comment]
Changes have been made, DNS TTL for the record is 60 seconds so the change should be reflected now.

**Comment by groupdocscloud** [comment]
@ewdurbin 

Thank you very much for your continuous quality support. Email verification issue is resolved.

**Comment by weegreenblobbie** [comment]
This is still a problem for me, I'm using a yahoo email address and the verification emails do not show up and are not showing up in the spam folders.  Please help.

**Comment by ewdurbin** [comment]
@weegreenblobbie what is your PyPI username?

**Comment by weegreenblobbie** [comment]
weegreenblobbie

**Comment by ewdurbin** [comment]
@weegreenblobbie we are showing three successful deliveries to a yahoo.com address for your account.

I also tested with my own yahoo.com address and was able to successfully receive a verification on the first try. Are you positive that these are not ending up in spam or caught by some filter?

**Comment by weegreenblobbie** [comment]
@ewdurbin oops, you are correct, I had too many different folders for spam, I'm not using my yahoo account much these days, thanks!
