### ISSUE TITLE
Safari & Firefox: Badge on Release History Page not Rendering Correctly

### ISSUE THREAD

**Issue by sbdchd** [pypa/warehouse#5237]
**Describe the bug**

This is a UI bug with Safari 12.0.2 & Firefox 64.0b9 where the release history badge is wrapping.

For example: https://pypi.org/project/Django/#history

In Safari:

<img width="692" alt="screenshot 2018-12-28 17 21 45" src="https://user-images.githubusercontent.com/7340772/50529752-2bbaac80-0ac5-11e9-9d76-a902013b81fa.png">

In Firefox:
<img width="715" alt="screenshot 2018-12-28 17 24 57" src="https://user-images.githubusercontent.com/7340772/50529815-be5b4b80-0ac5-11e9-80f7-1c2414a52c6f.png">

**Expected behavior**

The badge should not wrap like in Chrome:
<img width="552" alt="screenshot 2018-12-28 17 27 13" src="https://user-images.githubusercontent.com/7340772/50529828-d3d07580-0ac5-11e9-94d6-5fd74f3a4c64.png">

**To Reproduce**

Visit:  https://pypi.org/project/Django/#history

In Safari or Firefox at the versions listed above. I haven't tested it in any other versions.

**My Platform**

- Safari 12.0.2 
- Firefox 64.0b9
- Chrome 71.0.3578.98 

**Additional context**

This can be fixed by updating the `.badge` css class to have `white-space: nowrap;`, although I haven't checked to see if there are implications with this change in other parts of the site. 

---

**Good First Issue**: This issue is good for first time contributors. If you've already contributed to Warehouse, work on [another issue without this label](https://github.com/pypa/warehouse/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22good+first+issue%22) instead. If there is not a corresponding pull request for this issue, it is up for grabs. For directions for getting set up, see our [Getting Started Guide](https://warehouse.pypa.io/development/getting-started/). If you are working on this issue and have questions, feel free to ask them here, [`#pypa-dev` on Freenode](https://webchat.freenode.net/?channels=%23pypa-dev), or the [pypa-dev mailing list](https://groups.google.com/forum/#!forum/pypa-dev).

**Screenshot Required**: *If your pull request makes a visual change*, include a screenshot of your update. This helps our team give you feedback faster.

**Comment by di** [comment]
Thanks for the report @sbdchd. I've marked this as a ["good first issue"](https://github.com/pypa/warehouse/labels/good%20first%20issue).

**Comment by ip4368** [comment]
This seems to be fixed, I tested this on Firefox 68.0.1 and Safari 12.1.2, they look fine.

**Comment by di** [comment]
@nlhkabu Can you confirm this was fixed? I'm not seeing what change would have fixed this.

**Comment by nlhkabu** [comment]
No, this is not fixed.  If you enter a longer piece of text in the badge it's possible to reproduce - on all browsers.

This is going to be an issue for localisation where the text in this badge will be longer - for example, in French:

![Screenshot from 2019-08-05 06-33-48](https://user-images.githubusercontent.com/3323703/62441219-2d2f1000-b74b-11e9-9a2d-5d5703594159.png)

I've therefore added this ticket to the localisation milestone for the OTF contract.
