### ISSUE TITLE
Weblate settings: please link up `es` and its regional variants to avoid people creating duplicate translations

### ISSUE THREAD

**Issue by fitojb** [pypa/warehouse#8493]
https://hosted.weblate.org/projects/pypa/warehouse/es_419/#history

Someone has wrongly created a “Latin American Spanish” (es_419) translation, which is of course a useless duplication of localization efforts because the existing Spanish (es) translation has been 100% complete for a long time (although weirdly not deployed in the live site) and is free of any localisms.

Please remove the duplicate translation and link up the locales [1] so this doesn’t happen again.

[1] docs.weblate.org/en/latest/admin/config.html#simplify-languages

**Comment by fitojb** [comment]
Since #8208 has been pending merging and deploying for a long time, maybe that prompted the person at Weblate to create the redundant translation, since the live site displays a lot of English strings.

**Comment by di** [comment]
Thanks for the heads up. I've merged #8208 and removed the `es_419` locale.

Since we use hosted Weblate, it's not clear to me how to set `SIMPLIFY_LANGUAGES`, any ideas?

**Comment by fitojb** [comment]
Thanks for merging the update, @di!! However, I can still see English text in e.g. https://pypi.org/sponsor after setting the Spanish locale.

I’ll ask Nijel about setting the variable.

**Comment by di** [comment]
Yep, that's due to https://github.com/pypa/warehouse/issues/7455
